#!/usr/bin/env php
<?php

include '../jf/Core/Autoloader.php';
include '../jf/FileSystem/Dir.php';
include '../jf/Core/Config.php';
include '../jf/Core/Terminal.php';

JF\Terminal::run( $argv, __DIR__ );
